### ISSUE TITLE
Payment completion block is never called, Since i got an error like "PayUCollectPaymentVC.swift]:421 handlePureS2SResult(_:forApi:) -> error("Error in decoding payment response")" 

### ISSUE THREAD

**Issue by guru-mtech** [payu-intrepos/payu-upi-ios-sdk#3]
![Screenshot 2020-06-24 at 10 43 03 PM](https://user-images.githubusercontent.com/64658840/85601944-7db5a180-b66c-11ea-8283-5270f821f84e.png)

`fileprivate func setupPaymentCompletionHandler() {
        PayUUPICore.shared.paymentCompletion = { [weak self] result in
            DispatchQueue.main.async { [weak self] in
                guard let self = self else {return}
                self.parent?.navigationController?.backToViewController(viewController: PaymentHomeVC.self)
                switch result {
                case .success(let response):
                    Helper.showAlert(String(describing: response), onController: self.parent!)
                case .failure(let error):
                    Helper.showAlert(String(describing: error.description), onController: self.parent!)
                }
            }
        }
    }`

**Comment by Nikita-0411** [comment]
I am facing the same issue as well, did you find the solution ?

**Comment by DishaMukherjee** [comment]
@guru-mtech You can check now This issue has been resolved by our team.

**Comment by ashish121rock** [comment]
Still not resolve. I am getting this - 
{"status": "failure","unmappedstatus": "failed","error_Message":"Error in decoding payment response"}

**Comment by ShubhGar** [comment]
This is due to some configuration. Please connect at mobile.integration@payu.in.

**Comment by RatheshKannan** [comment]
I am facing the same issue  (IOS)

**Comment by AmitPayU** [comment]
@RatheshKannan , This is due to some configuration. Please reach us at [mobile.integration@payu.in] for more help.
